# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
  - oldrel

repos:
  CRAN: https://cran.rstudio.com
  
warnings_are_errors: false

deploy.skip_cleanup: true

os:
  - linux

sudo: true
dist: bionic

cache:
  - packages

before_install:
    - sudo apt-get install -y udunits-bin libproj-dev libgdal-dev libgeos-dev libudunits2-dev gdal-bin
    - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'
    
latex: true
pandoc: true

notifications:
  email:
    on_success: never
    on_failure: never

r_github_packages:
  - r-lib/covr

after_success:
      - travis_wait 30 Rscript -e 'covr::codecov()'

#addons:
#  apt_packages:
#      - libgdal-dev
#      - libproj-dev
#      - libgeos-dev
#      - libudunits2-dev
#      - gdal-bin
